WORKFLOW_USER_HOME=/opt/workflows
WORKFLOW_HOME=$WORKFLOW_USER_HOME/automatic-workflow
WEBDATADIR=$WORKFLOW_USER_HOME/ARKIV
WEBDANICA_VERSION=1.1-RC9
HADOOP_BINBIN=$WORKFLOW_USER_HOME/hadoop-1.2.1/
PIG_HOME=$WORKFLOW_USER_HOME/pig-0.16.0/
#PIG_HOME=/usr/
BUSYFILE=$WORKFLOW_HOME/.busy
WORKDIR=$WORKFLOW_HOME/working
OLDJOBSDIR=$WORKFLOW_HOME/oldjobs
FAILEDJOBS=$OLDJOBSDIR/failures
OKJOBS=$OLDJOBSDIR/successes
JAVA_HOME=/opt/workflows/jdk1.7.0_80
PATH=$JAVA_HOME/bin:$PATH
FINDLOGS_SCRIPT=${WORKFLOW_HOME}/findharvestlogs.sh
AUTOMATIC_SCRIPT=${WORKFLOW_HOME}/automatic.sh
WEBDANICA_LIBDIR=${WORKFLOW_HOME}/lib
export WORKFLOW_HOME WEBDATADIR WEBDANICA_VERSION HADOOP_BINBIN PIG_HOME BUSYFILE WORKDIR OLDJOBSDIR JAVA_HOME PATH FINDLOGS_SCRIPT AUTOMATIC_SCRIPT
mkdir -pv $WORKFLOW_HOME/criteria-results-automatic
mkdir -pv $WORKFLOW_HOME/SEQ_AUTOMATIC
mkdir -pv $WORKFLOW_HOME/logs
mkdir -pv $WORKFLOW_HOME/reports
mkdir -pv $WORKFLOW_HOME/working
mkdir -pv $OLDJOBSDIR
mkdir -pv $OKJOBS
mkdir -pv $FAILEDJOBS
